Farma-Authoring-Tool/farma-api

.editorconfig
run

- The run file contains alias to docker commands

Setup editor config and convenient script

---

README.md

##Qual Issue é? (obrigatório)
12
##Qual é esta Branch? (obrigatório)
isabela-tvitek/12/docs/created_project_readme
##Qual FEATURE foi feita nesta Branch? (obrigatório)
Foi criado o README do projeto

docs(api): created the project readme

---

app/controllers/teams_controller.rb

Issue: #14 
Add new member to FARMA
has been tested using the already defined linters tests
---

chore(api): add new member to FARMA

---

app/controllers/api/professors/exercises_controller.rb
app/models/exercise.rb
app/models/lo.rb
config/routes.rb
db/migrate/20231014210307_create_exercises.rb
db/schema.rb
test/controllers/api/professors/exercise/create_test.rb
test/controllers/api/professors/exercise/destroy_test.rb
test/controllers/api/professors/exercise/index_test.rb
test/controllers/api/professors/exercise/show_test.rb
test/controllers/api/professors/exercise/update_test.rb
test/controllers/api/professors/los/create_test.rb
test/factories/exercises.rb
test/models/exercise_test.rb
test/models/lo_test.rb

Issue: #**21**
created crud exercises
this crud was created to allow teachers to add exercises to their lo
was tested by creating unitary tests
---

@it/21/feat/exercises crud

---

app/controllers/api/professors/exercises_controller.rb
app/controllers/api/professors/solution_steps_controller.rb
app/models/solution_step.rb
config/routes.rb
db/migrate/20231031021853_create_solution_steps.rb
db/schema.rb
test/controllers/api/professors/exercise/update_test.rb
test/controllers/api/professors/los/create_test.rb
test/controllers/api/professors/solution_step/create_test.rb
test/controllers/api/professors/solution_step/destroy_test.rb
test/controllers/api/professors/solution_step/index_test.rb
test/controllers/api/professors/solution_step/show_test.rb
test/controllers/api/professors/solution_step/update_test.rb
test/factories/solution_steps.rb
test/models/exercise_test.rb
test/models/solution_step_test.rb

Issue: #**23**
In this pr, the crud was created for the solution steps of each exercise
This crud was created to allow teachers to create n questions in each exercise
This task was tested manually and with the help of unit tests that were created
---

@it/23/feat/solution steps crud

---

app/controllers/api/professors/introductions_controller.rb
app/models/introduction.rb
config/routes.rb
test/controllers/api/professors/introductions/destroy_test.rb
test/controllers/api/professors/introductions/duplicate_test.rb
test/models/introduction_test.rb

Issue: #**36**
New function created to duplicate introductions
Allow the user to be able to duplicate a introductions
---

feat(api): created function to duplicate introductions

---

app/controllers/api/professors/exercises_controller.rb
app/controllers/api/professors/los_controller.rb
app/models/exercise.rb
app/models/introduction.rb
app/models/lo.rb
app/models/solution_step.rb
app/models/tip.rb
app/services/duplicate/base_duplicator.rb
app/services/duplicate/exercise_duplicator.rb
app/services/duplicate/lo_duplicator.rb
app/services/duplicate/solution_step_duplicator.rb
app/services/duplicate/tip_duplicator.rb
config/routes.rb
db/migrate/20231124000507_add_introductions_count_to_lo.rb
db/migrate/20231124000538_add_exercises_count_to_lo.rb
db/schema.rb
test/controllers/api/professors/los/destroy_test.rb
test/controllers/api/professors/los/duplicate_test.rb
test/models/lo_test.rb

Issue: #**38**
New function created to duplicate los
Allow the user to be able to duplicate a los
---

@it/38/feat/los duplicate

---

app/controllers/api/professors/tips_controller.rb
app/controllers/concerns/actions_messages.rb
app/models/solution_step.rb
config/locales/messages.pt-BR.yml
config/routes.rb
test/controllers/api/professors/solution_step/reorder_test.rb
test/models/solution_step_test.rb

Issue: #**40**
Created a new route that allows you to modify the position of the tips
Allow teachers to configure the order of tips
---

feat(api): route created to update the tip position

---

app/controllers/api/professors/solution_steps_controller.rb
app/models/exercise.rb
config/routes.rb
test/controllers/api/professors/solution_step/reorder_test.rb
test/controllers/api/professors/tip/reorder_test.rb
test/models/exercise_test.rb

Issue: #**42**
Created a new route that allows you to modify the position of the soluction steps
Allow teachers to configure the order of soluction steps
---

feat(api): route created to update the soluction steps position

---

.rubocop.yml
app/controllers/api/professors/los_controller.rb
app/models/lo.rb
app/models/logics/lo/pages.rb
config/routes.rb
test/controllers/api/professors/los/reorder_test.rb
test/models/lo_test.rb

Issue: #**44**
Created a new route that allows you to modify the position of the LO
Allow teachers to configure the order of LO
---

feat(api): route created to update the lo items position

---

app/controllers/api/professors/los_controller.rb
app/models/lo.rb
app/models/user.rb
db/migrate/20231215005410_add_user_to_los.rb
db/schema.rb
test/factories/los.rb

Issue: #**58**
configured the relationship between lo and user
limit los access only to their creators
this task was tested locally manually
---

feat(api): configured the relationship between lo and user

---

app/controllers/api/professors/tips_controller.rb
app/models/tip.rb
app/services/duplicate/tip_duplicator.rb
db/migrate/20231215225712_add_title_to_tips.rb
db/schema.rb
test/controllers/api/professors/tip/create_test.rb
test/controllers/api/professors/tip/update_test.rb
test/factories/tips.rb
test/models/solution_step_test.rb
test/models/tip_test.rb

Issue: #**60**
added titlein tips
motivated for the tip to have text
this task was tested locally manually
---

feat(api): add title tip

---

app/controllers/api/professors/solution_steps_controller.rb
test/controllers/api/professors/solution_step/create_test.rb
test/controllers/api/professors/solution_step/tips_display_mode_test.rb
test/controllers/api/professors/solution_step/update_test.rb

Issue: #**62**
change parameters from camelcase to Snakecase
changed to maintain correct standards
this task was tested locally manually
---

feat(api): change parameters from Camelcase to Snakecase

---

test/swagger/swagger.yml

Issue: #**56**
created API documentation
document each parameter and rotor of each route in the system
no testing required
---

@it/56/docs/documentation api

---

.rubocop.yml
app/controllers/api/view/professors/lo_controller.rb
app/controllers/api/view/teams/los_controller.rb
app/models/lo.rb
app/models/los_team.rb
app/models/team.rb
app/models/user.rb
app/models/users_team.rb
app/resources/los/view_lo_professor_resource.rb
config/routes.rb
db/migrate/20240410000707_add_teams.rb
db/migrate/20240410002140_add_los_teams.rb
db/migrate/20240410002934_add_users_teams.rb
db/schema.rb
test/controllers/api/view/professors/los_controller_test.rb
test/controllers/api/view/teams/lo_controller_test.rb
test/factories/los.rb
test/factories/los_team.rb
test/factories/team.rb
test/factories/user.rb
test/factories/users_team.rb
test/models/lo_test.rb
test/models/user_test.rb

Lo detail endpoint for professor
Issue: #67 
Lo detail for professor
Add teams model 
Refactoring in lo detail for student
Allow viewing of a learning object by professor
---

@dviniciusbonin/67/feat/add lo detail for professor

---

.rubocop.yml
app/controllers/api/view/guests/lo_controller.rb
app/resources/los/view_lo_guest_resource.rb
config/routes.rb
test/controllers/api/views/guests/lo_guest_controller_test.rb

Lo detail endpoint for guest
Issue: #69 
Lo detail for guest
Allow viewing of a learning object by guest
---

@dviniciusbonin/69/feat/add lo detail for guest

---

app/controllers/api/view/teams/solution_step_controller.rb
app/controllers/concerns/resources_by_current_user_teams.rb
app/models/solution_step.rb
app/models/solution_steps_visualization.rb
config/routes.rb
db/migrate/20240509002552_create_solution_steps_visualizations.rb
db/schema.rb
test/controllers/api/view/teams/solution_step_controller_test.rb
test/factories/solution_steps_visualization.rb
test/models/solution_step_test.rb
test/models/solution_steps_visuzalization_test.rb

Confirm view endpoint
Issue: #78 
Confirm view in solution step
Allow the student to confirm the view in a solution step
---
Hours Required: 2

@dviniciusbonin/78/feat/add confirm view endpoint

---

app/controllers/api/view/teams/solution_step_controller.rb
app/models/answer.rb
app/models/solution_step.rb
app/models/tip.rb
app/models/tips_visualization.rb
app/resources/answer_resource.rb
config/routes.rb
db/migrate/20240515015335_create_answers.rb
db/migrate/20240515022807_create_tips_visualizations.rb
db/schema.rb
lib/tasks/populate/los.rake
test/controllers/api/view/teams/solution_step_controller_test.rb
test/models/answer_test.rb
test/models/solution_step_test.rb
test/models/tip_test.rb
test/models/tips_visualization_test.rb

Add send answer endpoint for student
Issue: #80 
Send answer endpoint for student
Allow sending answer to solution step
---
Hours Required: 5

feat(api): add send answer endpoint

---

app/controllers/api/view/teams/tip_controller.rb
app/models/solution_step.rb
app/models/tip.rb
config/routes.rb
lib/tasks/populate/los.rake
test/controllers/api/view/teams/tip_controller_test.rb
test/models/tip_test.rb

Tips request endpoint
Issue: #82 
Tips request endpoint for student
Allow the student to request tips to solve the solution step
---
Hours Required: 4

@dviniciusbonin/82/feat/add tips request

---

app/controllers/api/view/professors/solution_step_controller.rb
app/models/answer.rb
config/routes.rb
docker-compose.yml
test/controllers/api/view/professors/solution_step_controller_test.rb

Add send answer endpoint for professor
Issue: #86
Send answer endpoint for professor
Allow sending answer to solution step
---
Hours Required: 3

@dviniciusbonin/86/feat/add send answer by professor

---

app/controllers/api/view/professors/tip_controller.rb
app/models/tip.rb
app/models/tips_visualization.rb
config/routes.rb
test/controllers/api/view/professors/tip_controller_test.rb

Tips request endpoint for professor
Issue: #87 
Tips request endpoint for professor
Allow the professor to request tips to solve the solution step
---
Hours Required: 2

feat(api): add tips request endpoint by professor

---

app/models/solution_steps_visualization.rb
config/routes.rb
test/controllers/api/view/professors/solution_step_controller_test.rb

Confirm view endpoint for professor
Issue: #89 
Confirm view in solution step
Allow the professor to confirm the view in a solution step
---
Hours Required: 2

feat(api): add confirm view endpoint for professor

---

app/controllers/api/view/guests/tip_controller.rb
config/routes.rb
test/controllers/api/view/guests/tip_controller_test.rb

Tips request endpoint for guest
Issue: #97 
Tips request endpoint for guest
Allow the guest to request tips to solve the solution step
---
Hours Required: 1

feat(api): add tips request endpoint by guest

---

app/controllers/api/view/guests/solution_step_controller.rb
config/routes.rb
test/controllers/api/view/guests/solution_step_controller_test.rb

Confirm view endpoint for guest
Issue: #98
Confirm view in solution step
Allow the guest to confirm the view in a solution step
---
Hours Required: 1

feat(api): add confirm view endpoint for guest

---

a
app/controllers/api/view/guests/solution_step_controller.rb
app/models/solution_step.rb
config/routes.rb
test/controllers/api/view/guests/solution_step_controller_test.rb

Add send answer endpoint for guest
Issue: #96
Send answer endpoint for guest
Allow sending answer to solution step
---
Hours Required: 1

feat(api): add send answer endpoint by guest

---

app/models/logics/lo/progress.rb

Fix completed solution steps filter
Issue: #104 
Fix completed solution steps filter
Fix completed solution steps filter, adding team and user
---
Hours Required: 2

fix(lo progress): fix completed solution steps filter
